---
- name: "Remove Percona Server and Dependencies"
  yum:
    name: Percona-Server-server-{{ mysql_version_major }}{{ mysql_version_minor }}
    state: removed
  when: mysql_version_major|int < 8

- name: "Cleanup MySQL Logs files"
  file:
    path: "{{ item }}"
    state: "absent"
  with_items:
    - /var/log/mysqld.log
    - /etc/my.cnf

- name: "Cleanup MySQL Data Dir"
  file:
    path: "{{ mysql_datadir }}"
    state: "absent"

